### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by kanaji** [kanaji/traveling_sales_city_c-#1]
Create a front page - same as in individual project

**Comment by Karol-Gor** [comment]
![image](https://user-images.githubusercontent.com/72876709/97119188-cbbbde00-170e-11eb-8168-1cef3eb6d62b.png)

**Comment by Karol-Gor** [comment]
![uksw_godlo_uczelni](https://user-images.githubusercontent.com/72876709/97119252-44229f00-170f-11eb-80f5-e6dd70f6c10a.png)
